apiVersion: v1
kind: Service
metadata:
  name: node-example-10-service
  labels:
    name: node-example-10-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: node-example-10
  type: NodePort